DEFAULT_WEB_HTML = [
    "<html>",
    "    <head>",
    "       <title>Welcome to Repeater API</title>",
    "    </head>",
    "    <style>",
    "        body {",
    "            margin: 0;",
    "            padding: 0;",
    "        }",
    "        .container {",
    "            display: flex;",
    "            justify-content: center;",
    "            align-items: center;",
    "            height: calc(100vh - 40px); ",
    "            width: calc(100vw - 40px); ",
    "            margin: 20px; ",
    "            border-radius: 10px;",
    "            background: linear-gradient(to right, #667eea, #764ba2);",
    "            position: relative; ",
    "            overflow: hidden; ",
    "            box-sizing: border-box;",
    "        }",
    "        .main-title {",
    "            color: white;",
    "            font-size: 6vw;",
    "            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.36);",
    "        }",
    "        .triangle {",
    "            position: absolute;",
    "            opacity: 0.1; ",
    "            filter: drop-shadow(0 0 10px rgba(0,0,0,0.3)); ",
    "            pointer-events: none; ",
    "            transition: all 0.5s ease; ",
    "        }",
    "        .plain-link {",
    "            text-decoration: none;",
    "            color: inherit;",
    "        }",
    "    </style>",
    "    <body>",
    "        <div class=\"container\" id=\"triangles-container\">",
    "            <a href=\"/docs\" class=\"plain-link\">",
    "                <h1 class=\"main-title\">",
    "                    Welcome to Repeater API",
    "                </h1>",
    "            </a>",
    "        </div>",
    "        <script>",
    "            function calculateTriangleCount() {",
    "                ",
    "                const screenArea = window.innerWidth * window.innerHeight;",
    "                const baseArea = 1200 * 800; ",
    "                const baseCount = 15; ",
    "                ",
    "                const ratio = screenArea / baseArea;",
    "                let count = Math.floor(baseCount * ratio);",
    "                ",
    "                count = Math.max(8, Math.min(30, count));",
    "                ",
    "                return count;",
    "            }",
    "            ",
    "            function createRandomTriangle() {",
    "                const container = document.getElementById('triangles-container');",
    "                const triangle = document.createElement('div');",
    "                ",
    "                const size = Math.random() * 100 + 50; ",
    "                const left = Math.random() * 100; ",
    "                const top = Math.random() * 100; ",
    "                ",
    "                const colors = ['#ffffff', '#ff6b6b', '#4ecdc4', '#45b7d1', '#96ceb4'];",
    "                const randomColor = colors[Math.floor(Math.random() * colors.length)];",
    "                ",
    "                triangle.className = 'triangle';",
    "                triangle.style.width = '0';",
    "                triangle.style.height = '0';",
    "                triangle.style.left = `${left}%`;",
    "                triangle.style.top = `${top}%`;",
    "                ",
    "                const direction = Math.random() > 0.5 ? 'top' : 'bottom';",
    "                if (direction === 'top') {",
    "                    triangle.style.borderLeft = `${size/2}px solid transparent`;",
    "                    triangle.style.borderRight = `${size/2}px solid transparent`;",
    "                    triangle.style.borderBottom = `${size}px solid ${randomColor}`;",
    "                } else {",
    "                    triangle.style.borderLeft = `${size/2}px solid transparent`;",
    "                    triangle.style.borderRight = `${size/2}px solid transparent`;",
    "                    triangle.style.borderTop = `${size}px solid ${randomColor}`;",
    "                }",
    "                ",
    "                triangle.style.transform = `rotate(${Math.random() * 360}deg)`;",
    "                ",
    "                container.appendChild(triangle);",
    "            }",
    "            ",
    "            ",
    "            function createTriangles() {",
    "                const count = calculateTriangleCount();",
    "                console.log(`Creating ${count} triangles for screen size: ${window.innerWidth}x${window.innerHeight}`);",
    "                ",
    "                const container = document.getElementById('triangles-container');",
    "                const existingTriangles = container.querySelectorAll('.triangle');",
    "                existingTriangles.forEach(triangle => triangle.remove());",
    "                ",
    "                for (let i = 0; i < count; i++) {",
    "                    createRandomTriangle();",
    "                }",
    "            }",
    "            ",
    "            ",
    "            document.addEventListener('DOMContentLoaded', function() {",
    "                createTriangles();",
    "                ",
    "                window.addEventListener('resize', function() {",
    "                    createTriangles();",
    "                });",
    "            });",
    "        </script>",
    "    </body>",
    "</html>",
]